services:
  jenkins:
    image: jenkins:0.0.1
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - back
    environment:
      - DOCKER_GID_ON_HOST=501 # Puedes obtener el GID de docker en tu host con el comando: id -g docker
      - VAULT_ADDR=http://vault:8200
    privileged: true

  
  vault:
    image: vault:1.13.3
    container_name: vault
    restart: on-failure
    ports:
      - "8201:8201"
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://vault:8200
    #command: vault server  -config=/vault/file/vault_config.hcl
    #user: "501"
    volumes:
      - vault-volume:/vault/data
    healthcheck:
      test: ["CMD", "vault", "status"]
      retries: 5
    networks:
      - back
      
volumes:
  jenkins_home:
  vault-volume:

networks:
  back:
